### ISSUE TITLE
dimensions

### ISSUE THREAD

**Issue by pouledodue** [PurplShip/py-caps#1]
what's the format of the `dimensions` parameter?

**Comment by DanH91** [comment]
Hi @pouledodue 
Here is a full example with the dimensions.

```python
parcel_characteristics = parcel_characteristicsType(
    weight=0.3,
    dimensions=dimensionsType(
        length=5,
        width=5,
        height=5,
    )
)
```

You can find more details on the types here: [https://doc.purplship.com/api/pycaps.html#pycaps.rating.parcel_characteristicsType](https://doc.purplship.com/api/pycaps.html#pycaps.rating.parcel_characteristicsType)

Hope this helps.

**Comment by DanH91** [comment]
Closing it. Let me know if it doesn't work.

**Comment by pouledodue** [comment]
thanks friend
